server:
  port: 8087
  servlet:
    context-path: /api/authorization
management:
  server:
    port: 8187
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
  liquibase:
    default-schema: authorization
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: authorization-app
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
jwt:
  secret: myJwtSecretKey1234567890
  expiration-ms: 86400000           # 24 часа

logging:
  level:
    root: INFO
    com.bank.authorization: DEBUG
